version: "2"
services:
  app:
    build: ./
    ports:
      - "3042:3042"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /usr/local/var/mongodb:/data/db
