version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: yarn build
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST 'ARCHIVE=../archive/$(date +%y-%m-%d--%H-%M-%S) && cd /var/www/pocketcraft.trade && echo "Archiving current to $ARCHIVE" && mkdir -p "$ARCHIVE" && cp -R . "$ARCHIVE" && rm -r "$ARCHIVE/node_modules" && git pull && yarn build && pm2 restart server'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
